echo "==== PING3 ===="
ssh ping3 "ps aux | grep -E '\-\-host' | grep -E '(Dataserver|PyroNameserver|feeder.py|process.py|action.py)'"
printf "\n"
echo "==== PING4 ===="
ssh ping4 "ps aux | grep -E '\-\-host' | grep -E '(Dataserver|PyroNameserver|feeder.py|process.py|action.py)'"
printf "\n"
echo "==== PING6 ===="
ssh ping6 "ps aux | grep -E '\-\-host' | grep -E '(Dataserver|PyroNameserver|feeder.py|process.py|action.py)'"
printf "\n"
echo "==== PING7 ===="
ssh ping7 "ps aux | grep -E '\-\-host' | grep -E '(Dataserver|PyroNameserver|feeder.py|process.py|action.py)'"
printf "\n"
